[logger]
level = "INFO"

[http]
host = "127.0.0.1"
port = "8080"

[storage]
type = "sql" # memory или sql
dsn = "postgres://calendar:calendar@localhost:5432/calendar?sslmode=disable"

[kafka]
brokers = ["localhost:9092"]
topic = "calendar.notifications"
groupID = "calendar-storer"

[scheduler]
interval = "30s"   # период сканирования БД
keepPeriod = "8760h" # события старше этого срока удаляются
